version: '3.4'

services:
  taskapi-server:
    image: taskapi-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7000:80"
    networks:
      - app-network

  proxy:
    image: taskapi-proxy
    depends_on:
      - taskapi-server
    volumes: 
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    networks:
      - app-network

networks:
  app-network:
    name: app-network